app = "tinycalc-backend"
primary_region = "sea"  # Choose a region close to your users
kill_signal = "SIGTERM"

[build]
  # Use the Dockerfile instead of buildpacks
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "tinycalc-backend.fly.dev"
  PORT = "8080"
  PHX_SERVER = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512